# -*- coding: utf-8 -*-
"""bing_image_crawler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LbS3tAhjPKdVCPSNgFLh7yyNmwNrRHBs
"""

!pip install icrawler

from icrawler.builtin import BingImageCrawler

bing_crawler = BingImageCrawler(
    downloader_threads=4,
    storage={'root_dir': 'C:/bus'} # value에 경로 입력
)
# filter

bing_crawler.crawl(keyword='bus', filters=None, offset=0, max_num=1000) # keyword에 검색어, max_num = 최대 파일수

